# Generated by Django 3.1.5 on 2021-05-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='bank_name',
        ),
    ]
