# Generated by Django 3.1.5 on 2021-05-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0002_remove_bankdetail_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_id',
            field=models.CharField(max_length=200),
        ),
    ]
